// <auto-generated />
namespace Cake.EntityFramework.TestProject.Postgres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Bad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bad));
        
        string IMigrationMetadata.Id
        {
            get { return "201601100203055_Bad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
