// <auto-generated />
namespace Cake.EntityFramework.TestProject.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V4));
        
        string IMigrationMetadata.Id
        {
            get { return "201705300328255_V4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
